export const DEFAULT_ROLE_PERMISSIONS = {
  'App Owner': {
    infrastructure: true,
    agencies: true,
    permissions: true,
    plans: true,
    global_features: true,
    hierarchy: true,
    analytics: true,
    messaging: true,
    calendar: true,
    profiles: true,
    web_profiles: true,
    device_setup: true,
    audit_logs: true,
    qa_hub: true,
    settings: true,
    referrals: true,
    inventory: true
  },
  'Agency Admin': {
    infrastructure: false,
    agencies: false,
    permissions: true,
    plans: false,
    global_features: false,
    hierarchy: true,
    analytics: true,
    messaging: true,
    calendar: true,
    profiles: true,
    web_profiles: true,
    device_setup: true,
    audit_logs: true,
    qa_hub: true,
    settings: true,
    referrals: true,
    inventory: true
  },
  'Senior Operator': {
    infrastructure: false,
    agencies: false,
    permissions: false,
    plans: false,
    global_features: false,
    hierarchy: false,
    analytics: false,
    messaging: false,
    calendar: true,
    profiles: true,
    web_profiles: true,
    device_setup: false,
    audit_logs: false,
    qa_hub: false,
    settings: false,
    inventory: false
  }
};
