/**
 * asteriskConfigGenerator.js
 *
 * Generuje pjsip.conf + extensions.conf z dat v DB (DeviceBinding + Profile).
 * Po vygenerování nahraje soubory na VPS přes SSH a reloadne Asterisk.
 *
 * Volá se automaticky při:
 *   - POST /api/sip/config/:bindingId  (nastavení SIP credentials)
 *   - DELETE /api/sip/config/:bindingId (smazání)
 *   - POST /api/sip/reload-asterisk    (ruční reload)
 *
 * Env proměnné:
 *   VPS_SSH_HOST     - IP VPS (env variable, no default)
 *   VPS_SSH_USER     - SSH uživatel (napr. root)
 *   VPS_SSH_KEY_PATH - cesta k private key (napr. /root/.ssh/id_rsa)
 *   VPS_SSH_PASSWORD - alternativa k private key
 *   ASTERISK_CONF_DIR - adresář konfigurace (výchozí: /etc/asterisk)
 *   ASTERISK_WS_PORT  - WebSocket port (výchozí: 8089)
 *   ASTERISK_SIP_PORT - SIP UDP port (výchozí: 5060)
 */

const { NodeSSH } = require('node-ssh');
const prisma       = require('./db');

const CONF_DIR  = process.env.ASTERISK_CONF_DIR  || '/etc/asterisk';
const WS_PORT   = process.env.ASTERISK_WS_PORT   || '8089';
const SIP_PORT  = process.env.ASTERISK_SIP_PORT  || '5060';
const VPS_HOST  = process.env.VPS_SSH_HOST        || 'localhost';
const VPS_USER  = process.env.VPS_SSH_USER        || 'root';

// ── Sanitizace hodnot vkládaných do Asterisk konfigurace ──────────────────────
// Config se nasazuje na VPS přes SSH heredoc (`cat > … << 'NEXUS_EOF'`). Jakýkoli
// nový řádek v interpolované hodnotě může heredoc předčasně ukončit a spustit
// zbytek jako shell (RCE), případně vložit libovolné Asterisk direktivy. Proto se
// KAŽDÁ hodnota z DB před vložením do configu striktně čistí. Pro validní data
// (alfanumerické sipUser, běžná jména) jsou tyto funkce no-op.
function sipId(v) {
  // Identifikátory endpointů/auth/aor/exten — pouze alfanumerika, pomlčka, podtržítko
  return String(v || '').replace(/[^A-Za-z0-9_-]/g, '');
}
function phoneId(v) {
  // Telefonní čísla — pouze číslice a vedoucí '+'
  return String(v || '').replace(/[^0-9+]/g, '');
}
function callText(v) {
  // Volný text v callerid/komentářích — zákaz nových řádků, uvozovek a řídicích znaků
  return String(v || '').replace(/[\r\n"\\;]/g, '').trim();
}
function confValue(v) {
  // Hodnota na jednom řádku (heslo) — zákaz nových řádků a řídicích znaků
  // eslint-disable-next-line no-control-regex -- řídicí znaky odstraňujeme záměrně
  return String(v || '').replace(/[\r\n\x00-\x1f]/g, '');
}
function hostId(v) {
  // SIP host/IP providera — jen znaky platné v hostname/IP a volitelný ':port'
  return String(v || '').replace(/[^A-Za-z0-9.:_-]/g, '');
}
const ALLOWED_CODECS = ['ulaw', 'alaw', 'g722', 'g729', 'opus', 'gsm'];
function codecList(v, fallback = 'ulaw,alaw') {
  const picked = String(v || '')
    .split(',')
    .map(c => c.trim().toLowerCase())
    .filter(c => ALLOWED_CODECS.includes(c));
  return picked.length ? picked.join(',') : fallback;
}

// ── Generátor pjsip.conf ──────────────────────────────────────────────────────

function generatePjsipConf(relays, operators, trunks = []) {
  const lines = [
    '; pjsip.conf — Auto-generated by Nexus Hub Backend',
    `; Vygenerováno: ${new Date().toISOString()}`,
    '; NEUPRAVUJTE RUČNĚ — změny budou přepsány při reloadu',
    '',
    '; ── Transporty ──────────────────────────────────────────────────────────',
    '[transport-udp]',
    'type=transport',
    'protocol=udp',
    `bind=0.0.0.0:${SIP_PORT}`,
    '',
    '[transport-tcp]',
    'type=transport',
    'protocol=tcp',
    `bind=0.0.0.0:${SIP_PORT}`,
    '',
    '[transport-ws]',
    'type=transport',
    'protocol=ws',
    'bind=0.0.0.0:8088',
    '',
    '[transport-wss]',
    'type=transport',
    'protocol=wss',
    `bind=0.0.0.0:${WS_PORT}`,
    '; cert_file a privkey_file jsou nastaveny v http.conf',
    '',
    '; ── Relay zařízení (Android) ─────────────────────────────────────────────',
  ];

  for (const relay of relays) {
    const sipUser     = sipId(relay.sipUser);
    const profileName = callText(relay.profileName);
    const sipPassword = confValue(relay.sipPasswordPlain);
    if (!sipUser) continue; // po sanitizaci prázdný identifikátor → přeskočit
    lines.push(
      `; ${profileName || sipUser}`,
      `[${sipUser}]`,
      'type=endpoint',
      'context=nexushub',
      'disallow=all',
      'allow=ulaw,alaw,g722',
      'transport=transport-udp,transport-ws,transport-wss',
      'direct_media=no',
      'rtp_symmetric=yes',
      'force_rport=yes',
      'ice_support=yes',
      `aors=${sipUser}`,
      `auth=${sipUser}-auth`,
      `callerid="${profileName || sipUser}" <${sipUser}>`,
      '',
      `[${sipUser}]`,
      'type=aor',
      'max_contacts=2',
      'qualify_frequency=60',
      'remove_existing=yes',
      '',
      `[${sipUser}-auth]`,
      'type=auth',
      'auth_type=userpass',
      `username=${sipUser}`,
      `password=${sipPassword}`,
      '',
    );
  }

  lines.push('; ── Web operátoři (JsSIP/WebRTC) ────────────────────────────────────────');
  for (const op of operators) {
    const sipUser     = sipId(op.sipUser);
    const sipPassword = confValue(op.sipPasswordPlain);
    if (!sipUser) continue;
    lines.push(
      `[${sipUser}]`,
      'type=endpoint',
      'context=nexushub',
      'disallow=all',
      'allow=ulaw,alaw,opus',
      'transport=transport-wss,transport-ws',
      'direct_media=no',
      'rtp_symmetric=yes',
      'force_rport=yes',
      'ice_support=yes',
      'use_avpf=yes',
      'media_encryption=dtls',
      'dtls_verify=fingerprint',
      'dtls_setup=actpass',
      'dtls_auto_generate_cert=yes',
      `aors=${sipUser}`,
      `auth=${sipUser}-auth`,
      `callerid="Operator" <${sipUser}>`,
      '',
      `[${sipUser}]`,
      'type=aor',
      'max_contacts=2',
      'qualify_frequency=60',
      'remove_existing=yes',
      '',
      `[${sipUser}-auth]`,
      'type=auth',
      'auth_type=userpass',
      `username=${sipUser}`,
      `password=${sipPassword}`,
      '',
    );
  }

  // ── Per-agenturní SIP trunky (BYOT) ─────────────────────────────────────────
  if (trunks.length) {
    lines.push('; ── SIP trunky providerů (příchozí přesměrované hovory) ──────────────────');
  }
  for (const trunk of trunks) {
    const id      = sipId(trunk.id);
    const host    = hostId(trunk.host);
    const port    = Number(trunk.port) || 5060;
    const codecs  = codecList(trunk.codecs);
    const user    = confValue(trunk.username);
    const pass    = confValue(trunk.password);
    const fromU   = confValue(trunk.fromUser) || user;
    const register = trunk.authMode !== 'ip';
    if (!id || !host) continue;

    lines.push(`; Trunk ${callText(trunk.name)} (agency ${sipId(trunk.agencyId)})`);

    if (register && user) {
      lines.push(
        `[trunk_${id}-auth]`,
        'type=auth',
        'auth_type=userpass',
        `username=${user}`,
        `password=${pass}`,
        '',
        `[trunk_${id}-reg]`,
        'type=registration',
        'transport=transport-udp',
        `outbound_auth=trunk_${id}-auth`,
        `server_uri=sip:${host}:${port}`,
        `client_uri=sip:${user}@${host}:${port}`,
        'retry_interval=60',
        '',
      );
    }

    lines.push(
      `[trunk_${id}-aor]`,
      'type=aor',
      `contact=sip:${host}:${port}`,
      '',
      `[trunk_${id}]`,
      'type=endpoint',
      'context=from-trunk',
      'disallow=all',
      `allow=${codecs}`,
      'direct_media=no',
      'rtp_symmetric=yes',
      'force_rport=yes',
      `aors=trunk_${id}-aor`,
      ...(register && user ? [`outbound_auth=trunk_${id}-auth`] : []),
      ...(fromU ? [`from_user=${fromU}`] : []),
      '',
      // Rozpoznání příchozích hovorů od providera podle jeho hostu/IP
      `[trunk_${id}-identify]`,
      'type=identify',
      `endpoint=trunk_${id}`,
      `match=${host}`,
      '',
    );
  }

  return lines.join('\n');
}

// ── Generátor extensions.conf ─────────────────────────────────────────────────

function generateExtensionsConf(relays, operators, trunks = []) {
  const lines = [
    '; extensions.conf — Auto-generated by Nexus Hub Backend',
    `; Vygenerováno: ${new Date().toISOString()}`,
    '; NEUPRAVUJTE RUČNĚ',
    '',
    '[general]',
    'static=yes',
    'writeprotect=no',
    '',
    '; ── Makro pro paralelní vyzvánění relay + operátor ──────────────────────',
    '[macro-relay-call]',
    'exten => s,1,NoOp(Příchozí hovor pro: ${ARG2} via ${ARG1})',
    ' same => n,Set(PJSIP_HEADER(add,X-Model-Name)=${ARG2})',
    ' same => n,Set(PJSIP_HEADER(add,X-Relay-Extension)=${ARG1})',
    ' same => n,Dial(PJSIP/${ARG1}&PJSIP/${ARG3},30,rT)',
    ' same => n,GotoIf($["${DIALSTATUS}" = "BUSY"]?busy)',
    ' same => n,GotoIf($["${DIALSTATUS}" = "NOANSWER"]?noanswer)',
    ' same => n,Hangup()',
    ' same => n(busy),Busy(5)',
    ' same => n(noanswer),Hangup(19)',
    '',
    '[nexushub]',
    '',
  ];

  // Relay endpointy — každý namapován na svůj profil (modelku) + první operátor volá zároveň
  const defaultOp = sipId(operators[0]?.sipUser) || 'op1';
  for (const relay of relays) {
    const sipUser  = sipId(relay.sipUser);
    const safeName = callText(relay.profileName || relay.sipUser).replace(/[^a-zA-Z0-9 _-]/g, '').trim();
    if (!sipUser) continue;
    lines.push(
      `; ${safeName}`,
      `exten => ${sipUser},1,Macro(relay-call,${sipUser},${safeName},${defaultOp})`,
      '',
    );
  }

  // Přímé volání na operátory
  for (const op of operators) {
    const sipUser = sipId(op.sipUser);
    if (!sipUser) continue;
    lines.push(
      `exten => ${sipUser},1,NoOp(Příchozí hovor na operátora ${sipUser})`,
      ` same => n,Dial(PJSIP/${sipUser},30,rT)`,
      ' same => n,Hangup()',
      '',
    );
  }

  // ── Odchozí hovory (operátorka → klient) ────────────────────────
  //
  // Vytáčí se <DID>*<číslo klienta>. Prefix vybírá, jaké číslo klient uvidí —
  // podle rozhodnutí to má být číslo modelky, tedy DID přiřazené jejímu profilu.
  //
  // Pravidlo vznikne JEN pro DID, která jsou v databázi (loadSipDataFromDB je
  // filtruje na active + profileId). Cokoli jiného propadne na _X. níž a hovor
  // se položí. Kdyby se caller ID bralo z toho, co pošle prohlížeč, mohla by
  // si operátorka nastavit libovolné cizí číslo — takhle ne.
  //
  // ZÁMĚRNĚ SE NENAHRÁVÁ: žádný MixMonitor. Kdyby se to měnilo, patří to
  // i do stránky o evidenci údajů.
  for (const trunk of trunks) {
    const trunkId = sipId(trunk.id);
    if (!trunkId) continue;
    for (const did of trunk.dids) {
      const number = phoneId(did.number);
      if (!number) continue;
      const safeName = callText(did.profileName || number).replace(/[^a-zA-Z0-9 _-]/g, '').trim();
      // Dvě podoby cílového čísla: holé číslice a E.164 s plusem. `X` je
      // v Asterisku jen číslice, takže samotné `*X.` by číslo s plusem
      // nechytilo a hovor by spadl na fallback.
      lines.push(`; Odchozí za ${number} (${safeName})`);
      for (const suffix of ['X.', '+X.']) {
        lines.push(
          `exten => _${number}*${suffix},1,NoOp(Odchozí hovor, klient uvidí ${number})`,
          ` same => n,Set(CALLERID(num)=${number})`,
          ` same => n,Set(CALLERID(name)=${safeName})`,
          ` same => n,Dial(PJSIP/\${EXTEN:${number.length + 1}}@trunk_${trunkId},60,rT)`,
          ' same => n,Hangup()',
        );
      }
      lines.push('');
    }
  }

  // Fallback
  lines.push(
    'exten => _X.,1,NoOp(Neznámé číslo: ${EXTEN})',
    ' same => n,Hangup(21)',
    '',
    '; ── Příchozí DID z veřejné sítě ────────────────────────────────────────',
    '[from-trunk]',
  );

  // DID mapování dle phoneNumber profilu
  for (const relay of relays) {
    const phoneNumber = phoneId(relay.phoneNumber);
    const sipUser     = sipId(relay.sipUser);
    if (phoneNumber && sipUser) {
      lines.push(
        `; ${callText(relay.profileName || relay.sipUser)}`,
        `exten => ${phoneNumber},1,Goto(nexushub,${sipUser},1)`,
      );
    }
  }

  // ── DID z per-agenturních trunků → operátoři TÉŽE agentury (BYOT) ───────────
  // Příchozí hovor přesměrovaný ze SIMky modelky na DID vyzvání operátory dané
  // agentury. Scoping podle agencyId zabraňuje tomu, aby DID agentury A vyzvánělo
  // operátory agentury B.
  for (const trunk of trunks) {
    const agentOps = operators
      .filter(o => o.agencyId && o.agencyId === trunk.agencyId)
      .map(o => sipId(o.sipUser))
      .filter(Boolean);
    for (const did of trunk.dids) {
      const number = phoneId(did.number);
      if (!number) continue;
      const safeName = callText(did.profileName || number).replace(/[^a-zA-Z0-9 _-]/g, '').trim();
      lines.push(`; DID ${number} → ${safeName} (agency ${sipId(trunk.agencyId)})`);
      if (agentOps.length) {
        const dialStr = agentOps.map(op => `PJSIP/${op}`).join('&');
        lines.push(
          `exten => ${number},1,NoOp(Příchozí DID ${number} pro ${safeName})`,
          ` same => n,Set(PJSIP_HEADER(add,X-Model-Name)=${safeName})`,
          ` same => n,Dial(${dialStr},30,rT)`,
          ' same => n,Hangup()',
        );
      } else {
        // Žádný operátor v agentuře — hovor slušně odmítni, ať nepadá jinam
        lines.push(`exten => ${number},1,Hangup(21)`);
      }
    }
  }

  const firstRelay = sipId(relays[0]?.sipUser);
  lines.push(
    '',
    '; Fallback — vše ostatní na první relay',
    firstRelay ? `exten => s,1,Goto(nexushub,${firstRelay},1)` : 'exten => s,1,Hangup(21)',
    'exten => _+XXXXXXXXXXXX,1,Goto(nexushub,' + (firstRelay || '_') + ',1)',
  );

  return lines.join('\n');
}

// ── Načtení dat z DB ──────────────────────────────────────────────────────────

async function loadSipDataFromDB(agencyId, decrypt) {
  const where = {
    active:  true,
    sipUser: { not: null },
    ...(agencyId ? { agencyId } : {}),
  };

  const bindings = await prisma.deviceBinding.findMany({
    where,
    select: {
      sipUser:     true,
      sipPassword: true,
      sipServer:   true,
      sipPort:     true,
      agencyId:    true,
      profile: { select: { name: true, phoneNumber: true } },
    },
    orderBy: { createdAt: 'asc' },
  });

  const relays     = [];
  const operators  = [];

  for (const b of bindings) {
    const plain = decrypt(b.sipPassword);
    if (!plain) continue;

    const entry = {
      sipUser:          b.sipUser,
      sipPasswordPlain: plain,
      sipServer:        b.sipServer,
      sipPort:          b.sipPort || 5060,
      agencyId:         b.agencyId || null,
      profileName:      b.profile?.name   || null,
      phoneNumber:      b.profile?.phoneNumber || null,
    };

    // Konvence: relay zařízení mají sipUser začínající "relay", operátoři "op"
    if (b.sipUser.startsWith('op')) {
      operators.push(entry);
    } else {
      relays.push(entry);
    }
  }

  // Per-agenturní SIP trunky (BYOT) + jejich DIDy namapované na profily.
  const trunkRows = (await prisma.sipTrunk.findMany({
    where: { active: true, ...(agencyId ? { agencyId } : {}) },
    include: {
      dids: {
        where: { active: true, profileId: { not: null } },
        include: { profile: { select: { name: true } } },
      },
    },
    orderBy: { createdAt: 'asc' },
  })) || [];

  const trunks = trunkRows.map(t => ({
    id:        t.id,
    agencyId:  t.agencyId,
    name:      t.name,
    host:      t.host,
    port:      t.port || 5060,
    authMode:  t.authMode === 'ip' ? 'ip' : 'register',
    username:  t.username || null,
    // heslo je šifrované stejně jako sipPassword (sipEncryption)
    password:  t.password ? decrypt(t.password) : null,
    fromUser:  t.fromUser || t.username || null,
    codecs:    t.codecs || 'ulaw,alaw',
    dids:      t.dids.map(d => ({ number: d.number, profileName: d.profile?.name || null })),
  }));

  return { relays, operators, trunks };
}

// ── SSH deploy ────────────────────────────────────────────────────────────────

async function deployToVPS(pjsipConf, extensionsConf) {
  const ssh = new NodeSSH();

  const connectionConfig = {
    host:     VPS_HOST,
    username: VPS_USER,
  };

  if (process.env.VPS_SSH_KEY_PATH) {
    connectionConfig.privateKeyPath = process.env.VPS_SSH_KEY_PATH;
  } else if (process.env.VPS_SSH_PASSWORD) {
    connectionConfig.password = process.env.VPS_SSH_PASSWORD;
  } else {
    throw new Error('Chybí VPS_SSH_KEY_PATH nebo VPS_SSH_PASSWORD v .env');
  }

  await ssh.connect(connectionConfig);

  try {
    // Backup stávajících konfiguračních souborů
    await ssh.execCommand(`cp ${CONF_DIR}/pjsip.conf ${CONF_DIR}/pjsip.conf.bak 2>/dev/null || true`);
    await ssh.execCommand(`cp ${CONF_DIR}/extensions.conf ${CONF_DIR}/extensions.conf.bak 2>/dev/null || true`);

    // Zápis nových konfigurací
    await ssh.execCommand(`cat > ${CONF_DIR}/pjsip.conf << 'NEXUS_EOF'\n${pjsipConf}\nNEXUS_EOF`);
    await ssh.execCommand(`cat > ${CONF_DIR}/extensions.conf << 'NEXUS_EOF'\n${extensionsConf}\nNEXUS_EOF`);

    // Reload Asterisku (bez restartu — přijímá hovory dál)
    const { stdout, stderr } = await ssh.execCommand('asterisk -rx "pjsip reload" && asterisk -rx "dialplan reload"');
    console.log('[Asterisk] Reload output:', stdout || stderr);

    return { ok: true, output: stdout || '' };
  } finally {
    ssh.dispose();
  }
}

// ── Hlavní export ─────────────────────────────────────────────────────────────

/**
 * Regeneruje Asterisk konfiguraci z DB a nasadí na VPS.
 * @param {object} options
 * @param {string|null} options.agencyId - omezit na agenturu (null = všechny)
 * @param {function} options.decrypt - decrypt funkce ze sipEncryption
 */
async function regenerateAsteriskConfig({ agencyId = null, decrypt } = {}) {
  const { relays, operators, trunks } = await loadSipDataFromDB(agencyId, decrypt);

  if (relays.length === 0 && operators.length === 0 && trunks.length === 0) {
    console.warn('[Asterisk] Žádná SIP zařízení ani trunky v DB — přeskakuji generování');
    return { ok: true, skipped: true, message: 'Žádná SIP data' };
  }

  const pjsipConf      = generatePjsipConf(relays, operators, trunks);
  const extensionsConf = generateExtensionsConf(relays, operators, trunks);

  console.log(`[Asterisk] Generuji config: ${relays.length} relay(s), ${operators.length} operator(s), ${trunks.length} trunk(s)`);

  if (!process.env.VPS_SSH_HOST) {
    // Dev mode — vrátíme config bez SSH deploye
    console.warn('[Asterisk] VPS_SSH_HOST není nastaven — vracím pouze vygenerovaný config (bez nasazení)');
    return { ok: true, dryRun: true, pjsipConf, extensionsConf };
  }

  return await deployToVPS(pjsipConf, extensionsConf);
}

module.exports = { regenerateAsteriskConfig, generatePjsipConf, generateExtensionsConf };
