#!/bin/bash
#
# sync-server-to-prod.sh — bezpečně přenese server/ z monorepa (origin/nexus-sync)
# na produkci (live/nexus-backend) jako PR.
#
# PROČ ne `git subtree push`: jakmile se obě repa rozejdou (např. když se do
# nexus-backend mergne PR přímo, mimo monorepo), subtree push skončí na
# non-fast-forward a jediná „oprava" by byl force push, který na produkci maže
# práci. Tenhle skript místo toho udělá forward-port jako PR:
#   1. ověří, že produkce nemá ŽÁDNÉ SOUBORY navíc oproti monorepo server/ (nic se nesmaže),
#   2. vytvoří commit, jehož strom = monorepo server/ (z origin/master), s rodičem live/master,
#   3. pushne větev na live a otevře PR (merge PR = deploy na prod).
#
# Monorepo (origin) je zdroj pravdy pro server/. Viz docs/repo-sync.md.

set -euo pipefail

REMOTE=live
BASE=master
BACKEND_REPO=Zdenekdi/nexus-backend
BRANCH="sync/server-$(date +%Y%m%d-%H%M%S)"

echo "🔄 Fetchuji ${REMOTE} + origin…"
git fetch "$REMOTE" -q
git fetch origin -q   # zdroj je origin/master:server (ne lokální, možná zastaralý master)

# 1) Superset check — žádný soubor na produkci, který monorepo server/ nemá.
PROD_ONLY=$(comm -23 \
  <(git ls-tree -r --name-only "${REMOTE}/${BASE}" | sort) \
  <(git ls-tree -r --name-only "origin/${BASE}:server" | sort) || true)
if [ -n "$PROD_ONLY" ]; then
  echo "❌ Produkce (${REMOTE}/${BASE}) má soubory, které monorepo server/ NEMÁ."
  echo "   Sync by je smazal — nejdřív je backportuj do monorepa. Soubory:"
  echo "$PROD_ONLY" | sed 's/^/     - /'
  exit 1
fi

# 2) Commit se stromem = monorepo server/ (z origin/master), parent = prod master.
TREE=$(git rev-parse "origin/${BASE}:server")
if git diff --quiet "${REMOTE}/${BASE}" "$TREE"; then
  echo "✅ Produkce už je v souladu s monorepo server/ — není co syncovat."
  exit 0
fi

COMMIT=$(git commit-tree "$TREE" -p "${REMOTE}/${BASE}" \
  -m "chore(sync): forward-port monorepo server/ to production")
git update-ref "refs/heads/${BRANCH}" "$COMMIT"

echo "📊 Změny oproti produkci:"
git diff --stat "${REMOTE}/${BASE}" "$COMMIT" | tail -20

# 3) Push větve + PR.
echo "⬆️  Pushuji větev ${BRANCH} na ${REMOTE}…"
git push "$REMOTE" "$BRANCH"

if command -v gh >/dev/null 2>&1; then
  gh pr create --repo "$BACKEND_REPO" --base "$BASE" --head "Zdenekdi:${BRANCH}" \
    --title "chore(sync): forward-port monorepo server/ to production" \
    --body "Automated forward-port sync of \`server/\` from the monorepo (origin). Merging this deploys to production. Generated by scripts/sync-server-to-prod.sh."
  echo "✅ PR otevřen. Po review ho mergni → spustí deploy."
else
  echo "ℹ️  gh CLI není — otevři PR ručně: ${BACKEND_REPO}, base ${BASE}, head ${BRANCH}."
fi
